import Mahjong.GlobalSuccessorBridge

set_option autoImplicit false

namespace Mahjong.CachedTransitionQuotient
open GlobalEnumeration GlobalSuccessorBridge CanonicalCoverage GlobalOrbitKey
open GlobalOrbitUniqueness Generators LocalSymmetryFrame SafeGame

def encode (c : Certificate) (s : SafePosition) : PackedRules.Packed :=
  key (inventoriesOf c) s.val

/-- The graph generated by the checked local caches, the SAFE filter and the
orbit key. Its source witnesses are retained states; every original SAFE
state has such a representative. Optimized C++ lookups are separate. -/
def Move (c : Certificate) (data : Nat → SuccessorCache.Data)
    (a b : PackedRules.Packed) : Prop :=
  ∃ s q : State, Valid s ∧ IsSafe s ∧ Retained c s ∧
    key (inventoriesOf c) s = a ∧ Edge c data s q ∧ key (inventoriesOf c) q = b

theorem path_move (path : List Generator) {s t : State} (edge : SafeMove s t) :
    SafeMove (applyPath path s) (applyPath path t) := by
  induction path generalizing s t with
  | nil => exact edge
  | cons g path ih => exact ih (Symmetry.rename_safeStep g.renaming edge)

theorem transport_edge (s r q : State) (orbit : SameOrbit s r) (edge : SafeMove r q) :
    ∃ t, SafeMove s t ∧ SameOrbit t q := by
  obtain ⟨path,eq⟩ := orbit
  have moved := path_move path.reverse edge
  have back : applyPath path.reverse r = s := by rw [eq,reverse_path]
  rw [back] at moved
  exact ⟨applyPath path.reverse q,moved,sameOrbit_symm q _ ⟨path.reverse,rfl⟩⟩

theorem forward (c : Certificate) (data : Nat → SuccessorCache.Data)
    (checked : GlobalSuccessorBridge.Checked c data) {s t : SafePosition}
    (edge : RestrictedSafeMove s t) : Move c data (encode c s) (encode c t) := by
  obtain ⟨r,path,vr,sr,eq,kept⟩ := every_safe_has_retained_representative
    c.core c.summary c.raw c.ids c.members c.coreSizes c.safeChecked
    c.inventorySizes c.inventoryChecked s.val s.property.1 s.property.2
  have mapped : SafeMove r (applyPath path t.val) := by
    rw [eq]
    exact path_move path edge
  obtain ⟨q,cached,orbit⟩ := edge_complete c data checked r _ vr kept mapped
  have source := key_sameOrbit (inventoriesOf c) c.inventoryChecked c.inventorySizes c.sharedKeys
    s.val r s.property.1 ⟨path,eq⟩
  have target := key_sameOrbit (inventoriesOf c) c.inventoryChecked c.inventorySizes c.sharedKeys
    t.val q t.property.1 (sameOrbit_trans t.val _ q ⟨path,rfl⟩ orbit)
  exact ⟨r,q,vr,sr,kept,source,cached,target⟩

theorem backward (c : Certificate) (data : Nat → SuccessorCache.Data)
    (checked : GlobalSuccessorBridge.Checked c data) {s : SafePosition} {k : PackedRules.Packed}
    (edge : Move c data (encode c s) k) :
    ∃ t, RestrictedSafeMove s t ∧ encode c t = k := by
  obtain ⟨r,q,vr,sr,_,source,cached,target⟩ := edge
  have orbit : SameOrbit s.val r := (sameOrbit_iff_key_eq_on_safe
    c.core c.summary c.raw c.ids c.members c.coreSizes c.safeChecked
    c.inventorySizes c.inventoryChecked c.sharedMembers c.sharedKeys
    s.val r s.property.1 vr s.property.2 sr).mpr source.symm
  obtain ⟨v,real,vq,_⟩ := edge_sound c data checked r q vr cached
  obtain ⟨t,physical,tv⟩ := transport_edge s.val r v orbit real
  have vt : Valid t := step_target_valid physical.1
  have same := key_sameOrbit (inventoriesOf c) c.inventoryChecked c.inventorySizes c.sharedKeys
    t q vt (sameOrbit_trans t v q tv vq)
  exact ⟨⟨t,vt,physical.2⟩,physical,same.symm.trans target⟩

/-- Both directions hold from every valid SAFE physical representative. -/
theorem transition_quotient (c : Certificate) (data : Nat → SuccessorCache.Data)
    (checked : GlobalSuccessorBridge.Checked c data) :
    Quotient.TransitionQuotient RestrictedSafeMove (Move c data) (encode c) :=
  ⟨forward c data checked,backward c data checked⟩

theorem strategy_iff (c : Certificate) (data : Nat → SuccessorCache.Data)
    (checked : GlobalSuccessorBridge.Checked c data) (s : SafePosition) (o : Outcome) :
    NormalStrategy RestrictedSafeMove s o ↔ NormalStrategy (Move c data) (encode c s) o :=
  Quotient.normalStrategy_iff (transition_quotient c data checked)

/-- Conditional bridge only: this theorem does not supply a P/N certificate
or assume any historical output bit is correct. -/
theorem original_result_of_certificate (c : Certificate) (data : Nat → SuccessorCache.Data)
    (checked : GlobalSuccessorBridge.Checked c data)
    (rank : PackedRules.Packed → Nat) (label : PackedRules.Packed → Outcome)
    (cert : PNCertificate (Move c data) rank label) (rootP : label (encode c safeEmpty) = .P) :
    SecondPlayerWins Step Win empty :=
  original_second_player_wins_of_quotient_certificate (Move c data) (encode c) rank label
    (transition_quotient c data checked) cert rootP

end Mahjong.CachedTransitionQuotient

#print axioms Mahjong.CachedTransitionQuotient.path_move
#print axioms Mahjong.CachedTransitionQuotient.transport_edge
#print axioms Mahjong.CachedTransitionQuotient.forward
#print axioms Mahjong.CachedTransitionQuotient.backward
#print axioms Mahjong.CachedTransitionQuotient.transition_quotient
#print axioms Mahjong.CachedTransitionQuotient.strategy_iff
#print axioms Mahjong.CachedTransitionQuotient.original_result_of_certificate
