import Mahjong.GlobalOrbitKey

set_option autoImplicit false

namespace Mahjong.GlobalOrbitUniqueness
open CanonicalCoverage CanonicalInventory LocalCacheEncoding Base5Coverage Generators
open GlobalOrbitKey LocalSymmetryFrame PackedRules

structure Representative (t : Inventories) (s : State) : Prop where
  valid : Valid s
  kept : ∀ b, b < 4 → ∃ k, k < (t b).count ∧ (t b).member k = encodeBlock b s
  order01 : (t 0).id (encodeBlock 0 s) ≤ (t 0).id (encodeBlock 1 s)
  order12 : (t 0).id (encodeBlock 1 s) ≤ (t 0).id (encodeBlock 2 s)

def SameOrbit (s r : State) : Prop := ∃ path : List Generator, r = applyPath path s

theorem act_involutive (g : Generator) (s : State) : act g (act g s) = s := by
  funext u
  cases g with
  | reverseSuit a => exact congrArg s (reverseSuit_involutive a u)
  | swapSuits a c => exact congrArg s (swapSuits_involutive a c u)
  | swapHonors a c => exact congrArg s (swapHonors_involutive a c u)

theorem reverse_path (path : List Generator) (s : State) : applyPath path.reverse (applyPath path s) = s := by
  induction path generalizing s with
  | nil => rfl
  | cons g gs ih =>
    simp only [List.reverse_cons,path_append,applyPath]
    rw [ih,act_involutive]

theorem sameOrbit_refl (s : State) : SameOrbit s s := ⟨[],rfl⟩

theorem sameOrbit_symm (s r : State) (same : SameOrbit s r) : SameOrbit r s := by
  obtain ⟨path,eq⟩ := same
  exact ⟨path.reverse,by rw [eq,reverse_path]⟩

theorem sameOrbit_trans (s r u : State) (sr : SameOrbit s r) (ru : SameOrbit r u) : SameOrbit s u := by
  obtain ⟨a,ea⟩ := sr
  obtain ⟨b,eb⟩ := ru
  exact ⟨a++b,by rw [path_append,← ea]; exact eb⟩

theorem key_sameOrbit (t : Inventories) (checked : CanonicalCoverage.Checked t)
    (sizes : CanonicalCoverage.ProperSizes t) (shared : SharedKeys t)
    (s r : State) (valid : Valid s) (same : SameOrbit s r) : key t r = key t s := by
  obtain ⟨path,eq⟩ := same
  rw [eq]
  exact key_path t checked sizes shared path s valid

theorem retained_key (t : Inventories) (checked : CanonicalCoverage.Checked t) (s : State)
    (b : Nat) (hb : b < 4) (kept : ∃ k, k < (t b).count ∧ (t b).member k = encodeBlock b s) :
    blockKey t b s = (t b).id (encodeBlock b s) ∧
      (t b).member (blockKey t b s) = encodeBlock b s := by
  obtain ⟨k,hk,eq⟩ := kept
  have member := checked_member b (t b) (checked b hb) k hk
  have inside : encodeBlock b s < (t b).size := by rw [← eq]; exact member.1
  have fixed := ((retained_iff b (t b) (checked b hb) _ inside).mp ⟨k,hk,eq⟩).1
  have inv : (t b).id (encodeBlock b s) = k := by rw [← eq]; exact member.2
  simp only [blockKey,fixed,inv,eq,and_self]

theorem representative_order (t : Inventories) (checked : CanonicalCoverage.Checked t)
    (shared : SharedKeys t) (s : State) (rep : Representative t s) :
    (localKeys t s).a ≤ (localKeys t s).b ∧ (localKeys t s).b ≤ (localKeys t s).c := by
  have k0 := (retained_key t checked s 0 (by decide) (rep.kept 0 (by decide))).1
  have k1 := (retained_key t checked s 1 (by decide) (rep.kept 1 (by decide))).1
  have k2 := (retained_key t checked s 2 (by decide) (rep.kept 2 (by decide))).1
  simp only [localKeys,k0,k1,k2,(shared 1 (by decide)).2,(shared 2 (by decide)).2]
  exact ⟨rep.order01,rep.order12⟩

theorem representative_key_injective (t : Inventories) (checked : CanonicalCoverage.Checked t)
    (shared : SharedKeys t) (s r : State) (rs : Representative t s) (rr : Representative t r)
    (same : key t s = key t r) : s = r := by
  have os := representative_order t checked shared s rs
  have or := representative_order t checked shared r rr
  have keys := signature_sorted_injective (localKeys t s) (localKeys t r) os.1 os.2 or.1 or.2 same
  apply pack_injective s r rs.valid rr.valid
  apply packed_ext
  intro b hb
  rw [pack_get s b hb,pack_get r b hb]
  have ks := (retained_key t checked s b hb (rs.kept b hb)).2
  have kr := (retained_key t checked r b hb (rr.kept b hb)).2
  have sameBlockKey := congrArg (fun p : Packed => p.get b) keys
  rw [localKeys_get t s b hb,localKeys_get t r b hb] at sameBlockKey
  rw [← ks,← kr,sameBlockKey]

theorem representatives_in_same_orbit_equal (t : Inventories) (checked : CanonicalCoverage.Checked t)
    (sizes : CanonicalCoverage.ProperSizes t) (shared : SharedKeys t)
    (s r : State) (rs : Representative t s) (rr : Representative t r) (same : SameOrbit s r) : s = r :=
  representative_key_injective t checked shared s r rs rr (key_sameOrbit t checked sizes shared s r rs.valid same).symm

/-- Existence and uniqueness for the complete group generated by independent
numeric reflections, all suit transpositions and all honor transpositions. -/
theorem every_safe_has_unique_representative (core summary raw ids members : Nat → ByteArray)
    (coreSizes : Base5Coverage.ProperSizes core)
    (safeChecked : FullSafeData.Checked (Base5Coverage.tables core summary raw))
    (inventorySizes : CanonicalCoverage.ProperSizes (inventories raw ids members))
    (inventoryChecked : CanonicalCoverage.Checked (inventories raw ids members))
    (sharedMembers : SortedCoverage.SharedMembers (inventories raw ids members))
    (sharedKeys : SharedKeys (inventories raw ids members))
    (s : State) (valid : Valid s) (safe : IsSafe s) :
    ∃ r, Representative (inventories raw ids members) r ∧ IsSafe r ∧ SameOrbit s r ∧
      ∀ q, Representative (inventories raw ids members) q → SameOrbit s q → q = r := by
  obtain ⟨r,path,vr,sr,eq,kept,order⟩ := SortedCoverage.every_safe_sorted_representative
    core summary raw ids members coreSizes safeChecked inventorySizes inventoryChecked sharedMembers s valid safe
  have rep : Representative (inventories raw ids members) r := ⟨vr,kept,order.1,order.2⟩
  refine ⟨r,rep,sr,⟨path,eq⟩,?_⟩
  intro q qr qs
  exact representatives_in_same_orbit_equal _ inventoryChecked inventorySizes sharedKeys q r qr rep
    (sameOrbit_trans q s r (sameOrbit_symm s q qs) ⟨path,eq⟩)

theorem sameOrbit_iff_key_eq_on_safe (core summary raw ids members : Nat → ByteArray)
    (coreSizes : Base5Coverage.ProperSizes core)
    (safeChecked : FullSafeData.Checked (Base5Coverage.tables core summary raw))
    (inventorySizes : CanonicalCoverage.ProperSizes (inventories raw ids members))
    (inventoryChecked : CanonicalCoverage.Checked (inventories raw ids members))
    (sharedMembers : SortedCoverage.SharedMembers (inventories raw ids members))
    (sharedKeys : SharedKeys (inventories raw ids members))
    (s r : State) (vs : Valid s) (vr : Valid r) (ss : IsSafe s) (sr : IsSafe r) :
    SameOrbit s r ↔ key (inventories raw ids members) s = key (inventories raw ids members) r := by
  constructor
  · intro orbit
    exact (key_sameOrbit _ inventoryChecked inventorySizes sharedKeys s r vs orbit).symm
  · intro eq
    obtain ⟨p,rp,_,sp,_⟩ := every_safe_has_unique_representative core summary raw ids members
      coreSizes safeChecked inventorySizes inventoryChecked sharedMembers sharedKeys s vs ss
    obtain ⟨q,rq,_,rqOrbit,_⟩ := every_safe_has_unique_representative core summary raw ids members
      coreSizes safeChecked inventorySizes inventoryChecked sharedMembers sharedKeys r vr sr
    have same : key (inventories raw ids members) p = key (inventories raw ids members) q := by
      rw [key_sameOrbit _ inventoryChecked inventorySizes sharedKeys s p vs sp,
        key_sameOrbit _ inventoryChecked inventorySizes sharedKeys r q vr rqOrbit,eq]
    have pq := representative_key_injective _ inventoryChecked sharedKeys p q rp rq same
    subst q
    exact sameOrbit_trans s p r sp (sameOrbit_symm r p rqOrbit)

end Mahjong.GlobalOrbitUniqueness

#print axioms Mahjong.GlobalOrbitUniqueness.reverse_path
#print axioms Mahjong.GlobalOrbitUniqueness.sameOrbit_symm
#print axioms Mahjong.GlobalOrbitUniqueness.sameOrbit_trans
#print axioms Mahjong.GlobalOrbitUniqueness.key_sameOrbit
#print axioms Mahjong.GlobalOrbitUniqueness.retained_key
#print axioms Mahjong.GlobalOrbitUniqueness.representative_key_injective
#print axioms Mahjong.GlobalOrbitUniqueness.representatives_in_same_orbit_equal
#print axioms Mahjong.GlobalOrbitUniqueness.every_safe_has_unique_representative
#print axioms Mahjong.GlobalOrbitUniqueness.sameOrbit_iff_key_eq_on_safe
